
export const getTitle = () => cy.get('[data-cy="title"]')
export const getUserPicture = () => cy.get('[data-cy="user-picture"]')
export const getAlias = () => cy.get('[data-cy="alias"]')
export const getUpdateUserEmailSection = () => cy.get('[data-cy="user-email"]')
export const getUpdateUserEmailInput = () => cy.get('[data-cy="input-email"]')
export const getUpdateUserEmailConfirmModal = () => cy.get('[data-cy="email-update-modal"]')
export const getEmailConfirmModalCancelButton = () => cy.get('[data-cy="email-confirm-modal-cancel-button"]')
export const getEmailConfirmModalValidateButton = () => cy.get('[data-cy="email-confirm-modal-validate-button"]')
export const getDeleteUserAccountSection = () => cy.get('[data-cy="user-account"]')
export const getAliasConfirmModal = () => cy.get('[data-cy="alias-confirm-modal"]')
export const getAliasConfirmModalInput = () => cy.get('[data-cy="input-alias-confirm"]')
export const getAliasConfirmModalCancelButton = () => cy.get('[data-cy="alias-confirm-modal-cancel-button"]')
export const getAliasConfirmModalValidateButton = () => cy.get('[data-cy="alias-confirm-modal-validate-button"]')
