#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

nx run-many --target=e2e --all --nx-bail --parallel=false && nx run-many --target=test --all --watch=false --nx-bail --parallel && npm --prefix functions run test
